const { userType, serviceName } = require("../utils/enums");
const apiEnum = require("../utils/api_constant");

const precidency = {
  [userType.SUPER_ADMIN]: 50,
  [userType.ADMIN]: 40,
  [userType.RESELLER]: 30,
  [userType.COMPANY_ADMIN]: 20,
  [userType.USER]: 10,
};

const superAdmin = {
  [serviceName.BOT_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.COMPANY_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_LIST]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.FILE_SERVICE]: {
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
  },
  [serviceName.INVITATION_SERVICE]: {
    [apiEnum.INVITE_ADMIN]: true,
    [apiEnum.INVITE_RESELLER]: true,
    [apiEnum.INVITE_USER]: true,
    [apiEnum.INVITE_COMPANY_ADMIN]: true,
    [apiEnum.CHECK_PASSWORD]: true,
  },
  [serviceName.PACKAGE_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.THREAD_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.SUBSCRIPTION_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.STRIPE_BILLING_PORTAL]: true,
    [apiEnum.STRIPE_UPDATE_INFO]: true,
    [apiEnum.STRIPE_SUBSCRIPTION_INFO]: true,
  },
  [serviceName.USER_SERVICE]: {
    [apiEnum.REQUEST_SIGNUP]: true,
    [apiEnum.SIGNUP]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.CATEGORY_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
};

const admin = {
  [serviceName.BOT_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.COMPANY_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_LIST]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.FILE_SERVICE]: {
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
  },
  [serviceName.INVITATION_SERVICE]: {
    [apiEnum.INVITE_ADMIN]: false,
    [apiEnum.INVITE_RESELLER]: true,
    [apiEnum.INVITE_USER]: true,
    [apiEnum.INVITE_COMPANY_ADMIN]: true,
    [apiEnum.CHECK_PASSWORD]: true,
  },
  [serviceName.PACKAGE_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.THREAD_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.SUBSCRIPTION_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.STRIPE_BILLING_PORTAL]: true,
    [apiEnum.STRIPE_UPDATE_INFO]: true,
    [apiEnum.STRIPE_SUBSCRIPTION_INFO]: true,
  },
  [serviceName.USER_SERVICE]: {
    [apiEnum.REQUEST_SIGNUP]: true,
    [apiEnum.SIGNUP]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.CATEGORY_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
};

const companyAdmin = {
  [serviceName.BOT_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.COMPANY_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_LIST]: false,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.FILE_SERVICE]: {
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
  },
  [serviceName.INVITATION_SERVICE]: {
    [apiEnum.INVITE_ADMIN]: false,
    [apiEnum.INVITE_RESELLER]: false,
    [apiEnum.INVITE_COMPANY_ADMIN]: false,
    [apiEnum.INVITE_USER]: true,
    [apiEnum.CHECK_PASSWORD]: true,
  },
  [serviceName.PACKAGE_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_BY_ID]: false,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.THREAD_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.SUBSCRIPTION_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.STRIPE_BILLING_PORTAL]: true,
    [apiEnum.STRIPE_UPDATE_INFO]: true,
    [apiEnum.STRIPE_SUBSCRIPTION_INFO]: true,
  },
  [serviceName.USER_SERVICE]: {
    [apiEnum.REQUEST_SIGNUP]: true,
    [apiEnum.SIGNUP]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.CATEGORY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
};

const reseller = {
  [serviceName.BOT_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.COMPANY_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_LIST]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.FILE_SERVICE]: {
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
  },
  [serviceName.INVITATION_SERVICE]: {
    [apiEnum.INVITE_ADMIN]: false,
    [apiEnum.INVITE_RESELLER]: false,
    [apiEnum.INVITE_COMPANY_ADMIN]: true,
    [apiEnum.INVITE_USER]: true,
    [apiEnum.CHECK_PASSWORD]: true,
  },
  [serviceName.PACKAGE_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_BY_ID]: false,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.THREAD_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.SUBSCRIPTION_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.STRIPE_BILLING_PORTAL]: true,
    [apiEnum.STRIPE_UPDATE_INFO]: true,
    [apiEnum.STRIPE_SUBSCRIPTION_INFO]: true,
  },
  [serviceName.USER_SERVICE]: {
    [apiEnum.REQUEST_SIGNUP]: true,
    [apiEnum.SIGNUP]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.CATEGORY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
};

const user = {
  [serviceName.BOT_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.COMPANY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_LIST]: false,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.FILE_SERVICE]: {
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
  },
  [serviceName.INVITATION_SERVICE]: {
    [apiEnum.INVITE_ADMIN]: false,
    [apiEnum.INVITE_RESELLER]: false,
    [apiEnum.INVITE_COMPANY_ADMIN]: false,
    [apiEnum.INVITE_USER]: false,
    [apiEnum.CHECK_PASSWORD]: false,
  },
  [serviceName.PACKAGE_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_BY_ID]: false,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.THREAD_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.SUBSCRIPTION_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.STRIPE_BILLING_PORTAL]: false,
    [apiEnum.STRIPE_UPDATE_INFO]: false,
    [apiEnum.STRIPE_SUBSCRIPTION_INFO]: false,
  },
  [serviceName.USER_SERVICE]: {
    [apiEnum.REQUEST_SIGNUP]: true,
    [apiEnum.SIGNUP]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.CATEGORY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
};

const editor = {
  [serviceName.BOT_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.COMPANY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_LIST]: false,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.FILE_SERVICE]: {
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
  },
  [serviceName.INVITATION_SERVICE]: {
    [apiEnum.INVITE_ADMIN]: false,
    [apiEnum.INVITE_RESELLER]: false,
    [apiEnum.INVITE_COMPANY_ADMIN]: false,
    [apiEnum.INVITE_USER]: false,
    [apiEnum.CHECK_PASSWORD]: false,
  },
  [serviceName.PACKAGE_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_BY_ID]: false,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.THREAD_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.SUBSCRIPTION_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.STRIPE_BILLING_PORTAL]: false,
    [apiEnum.STRIPE_UPDATE_INFO]: false,
    [apiEnum.STRIPE_SUBSCRIPTION_INFO]: false,
  },
  [serviceName.USER_SERVICE]: {
    [apiEnum.REQUEST_SIGNUP]: true,
    [apiEnum.SIGNUP]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.CATEGORY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
};

const viewer = {
  [serviceName.BOT_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
    [apiEnum.UPLOAD]: false,
    [apiEnum.DELETE_FILE]: false,
  },
  [serviceName.COMPANY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_LIST]: false,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.FILE_SERVICE]: {
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
  },
  [serviceName.INVITATION_SERVICE]: {
    [apiEnum.INVITE_ADMIN]: false,
    [apiEnum.INVITE_RESELLER]: false,
    [apiEnum.INVITE_COMPANY_ADMIN]: false,
    [apiEnum.INVITE_USER]: false,
    [apiEnum.CHECK_PASSWORD]: false,
  },
  [serviceName.PACKAGE_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.GET_BY_ID]: false,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
  [serviceName.THREAD_SERVICE]: {
    [apiEnum.CREATE]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
    [apiEnum.UPLOAD]: true,
    [apiEnum.DELETE_FILE]: true,
  },
  [serviceName.SUBSCRIPTION_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: false,
    [apiEnum.STRIPE_BILLING_PORTAL]: false,
    [apiEnum.STRIPE_UPDATE_INFO]: false,
    [apiEnum.STRIPE_SUBSCRIPTION_INFO]: false,
  },
  [serviceName.USER_SERVICE]: {
    [apiEnum.REQUEST_SIGNUP]: true,
    [apiEnum.SIGNUP]: true,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: true,
    [apiEnum.DELETE_BY_ID]: true,
  },
  [serviceName.CATEGORY_SERVICE]: {
    [apiEnum.CREATE]: false,
    [apiEnum.GET_ALL]: true,
    [apiEnum.GET_BY_ID]: true,
    [apiEnum.UPDATE_BY_ID]: false,
    [apiEnum.DELETE_BY_ID]: false,
  },
};

module.exports = {
  precidency,
  superAdmin,
  admin,
  reseller,
  companyAdmin,
  user,
  editor,
  viewer,
};
